[package]
name = "rateio-api"
version = "0.1.0"
edition = "2024"

[dependencies]
rateio = { path = "../rateio/" }
actix-web = "4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
actix-cors = "0.7.1"
